#!/bin/bash

#############  CONSTANTES  #############
UTILS_MODULE=

SELF=`readlink $0 || echo $0`
SCRIPT_PATH=`dirname $SELF`

#supondo o script no root do repositorio
JARAKI_PATH=`cd $SCRIPT_PATH; pwd`

UTILS_MODULE=jaraki_utils
############# FUNCOES #############

function usage
{
	echo "Usage: `basename $0` [.erl file]
	[-h   | --help]  Prints this help

	prints de Erlang abstract format of the given file"
}

function print_east
{
	erl -pa $JARAKI_PATH/ebin -noshell -eval "jaraki_utils:print_erl_ast_from_erlang(\"$JARAKI_PATH/$filename\")." -s erlang halt
	echo ""
}

#############  VARIÁVEIS  #############
filename=

#############  SCRIPT  #############

# Foram passados parâmetros?
# $# -> quantidade de param.
if [ $# -eq 0 ]; then
	usage # executa funcao usage acima
	exit 1
fi

while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           usage
                                exit
                                ;;
        *.erl )                filename=$1
			  				   ;;
		* )						echo "*** Error: file especified \"$1\" has not .erl extension"
								echo "" #newline
								usage
								exit 1
    esac
    shift
done

if [ "$filename" == "" ]; then
	echo "*** Error: no file especified"
	echo ""
	usage
	exit 1
fi

print_east