#! /usr/bin/env escript

%% FALTANDO:
%%    - jaraki_compile retornar nome do arquivo gerado
%%    - script capturar nome do arquivo gerado e compilá-lo e rodá-lo

%% supondo o script no root do repositorio
-define(JARAKI_PATH, element(2, file:get_cwd())).
-define(LIBS_PATH, ?JARAKI_PATH ++ "/ebin").
%-define(JAVA_EBIN_PATH, ?JARAKI_PATH ++ "/java_beam/ebin/").
%-define(JAVA_ESRC_PATH, ?JARAKI_PATH ++ "/java_beam/src/").
-define(SCRIPT_NAME, filename:basename(escript:script_name())).
-define(COMPILE_OPTIONS(FileDir),
		[return_errors, nowarn_unused_vars, {outdir, FileDir}]).
		%, {outdir, ?JAVA_EBIN_PATH}]).
-define(ERROR(Msg),
			io:format(
					"*********ERROR!~n"
					"***Reason: ~p~n~n", [Msg])).

%%-----------------------------------------------------------------------------
%% Imprime a ajuda, indica o que esse escript faz...

help() ->
	io:format(""
	"Usage: "++?SCRIPT_NAME++" [options] [.beam file] [arg1 arg2 ...]\n"
	"\n"
	"Options:\n"
	"\t[-h | --help]  Prints this help\n\n"

	"Modes:\n"
	"\t.beam file: Compile and run a erlang compiled file generated with "
					"jaraki compiler\n\n"

	%% "\t.erl file: Compile and run a erlang source generated with "
	%% 				"jaraki compiler\n\n"

	"\t\tThe .erl file should be generated with the jaraki compiler.\n"
	"\t\tFirst I will compile the .erl file, then I will run it.\n\n"

	"\t\tI will run the main method (function) on it.\n\n"

	"\t\tIf especified, arg1, arg2, argN will be passed as arguments.\n"
	"\t\tIf no argument is especified, an empty list is passed.\n\n").

%%-----------------------------------------------------------------------------
%% Funcao principal, executada ao chamar escript

main([]) -> help();
main(["-h"| _]) -> help();
main(["--help"| _]) -> help();
main([FileName | Args]) ->
	case filename:extension(FileName) of
		".beam" ->
			load_libs(FileName, Args);
			%% nao precisa mais compilar os .erl, o jkc já faz isso!
			%%compile_erl_src(FileName, Args);
		_ ->
			?ERROR("Wrong file extension!\n\n")
	end.

%% compile_java_src(_,_) ->
%% 	io:format("to be finished...\n"
%% 				"jaraki:compile must return generated erlang file name...\n\n");

%% compile_erl_src(FileName, Args) ->
	%% io:format("Compiling erlang source...\n"),
	%% io:format("aff: ~p em ~p", [FileName, filename:dirname(FileName)]),
	%% case compile:file(FileName, ?COMPILE_OPTIONS(filename:dirname(FileName))) of
	%% 	{ok, ModuleName} ->
	%% 		io:format("done!\n\n"),
	%% 		load_libs(ModuleName, Args);

	%% 	{error, [{_, [{_,_,{_, enoent}}]}], _} ->
	%% 		Msg = "File not found!",
	%% 		?ERROR(Msg);

	%% 	{error, ErrorList, _WarningList} ->
	%% 		?ERROR(ErrorList)
	%% end.

load_libs(FileName, Args) ->
	%VERBOSE_OFF
	%io:format("Loading libs... "),

	case code:add_pathz(?LIBS_PATH) of
		true ->
			%VERBOSE_OFF
			%io:format("done!\n\n"),
			run(FileName, Args);

		{error, Reason} ->
			?ERROR("Cant load libs: " ++ Reason)
	end.

run(FileName, Args) ->
	%code:add_pathz(?JAVA_EBIN_PATH),
	code:add_pathz(filename:dirname(FileName)),
	ModuleName = list_to_atom(filename:basename(FileName, ".beam")),

	%VERBOSE_OFF
	%io:format(
	%		"Running Jaraki code, method main...\n"
	%		"---------------------------------------\n\n"),

	%StartTime = time_microseg(),
	ModuleName:main({{array, 'String'}, Args}).%,
	%EndTime = time_microseg(),

	%ElapsedTime = EndTime - StartTime,
	%VERBOSE_OFF
	%io:format(
	%		"\n"
	%			"---------------------------------------\n"
	%			"Execution finished with success!\n"
	%			"Execution time: ~p us (~p ms ou ~p s)"
	%		"\n\n",
	%		[ElapsedTime, round(ElapsedTime/1000), ElapsedTime/1000000]).

%% time_microseg() ->
%% 	{MS, S, US} = now(),
%% 	(MS * 1.0e+12) + (S * 1.0e+6) + US.

	% compile:file(File, Options)
	%	=>  {ok, ModuleName}
	%	=>  {error, ErrorList, WarningList}
	%	=>  {ok,ModuleName,Warnings}
	%
	%	opções úteis:
	%		return_errors  -> retorna {error, ErrorList, WrningList}
	%		{outdir, Dir}  -> óbvio
	%		{i, IncludeDir} -> ||
	%		nowarn_unused_vars

	% compile:forms(Forms, Options)
	%	análogo ao compile:file, mas recebe uma lista de forms em ABS Format
