-file("/usr/local/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(jaraki_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/jaraki_lexer.xrl", 107).

build_text(Type, Chars, Line, Length) ->
	Text = detect_special_char(lists:sublist(Chars, 2, Length - 2)),
	{token, {Type, Line, Text}}.

%% Detecta os caracteres especiais
detect_special_char(Text) ->
	detect_special_char(Text, []).
detect_special_char([], Output) ->
	lists:reverse(Output);
detect_special_char([$\\, SpecialChar | Rest], Output) ->
	Char = case SpecialChar of
		$\\	-> $\\;
		$/	-> $/;
		$\" -> $\";
		$\' -> $\';
		$b	-> $\b;
		$d	-> $\d;
		$e	-> $\e;
		$f	-> $\f;
		$n	-> $\n;
		$r	-> $\r;
		$s	-> $\s;
		$t	-> $\t;
		$v	-> $\v;
		_	->
			throw({error,
				{"unrecognized special character: ", [$\\, SpecialChar]}})
	end,
	detect_special_char(Rest, [Char|Output]);
detect_special_char([Char|Rest], Output) ->
	detect_special_char(Rest, [Char|Output]).

op(OpChar) ->
	case OpChar of
		"<=" -> '=<';
		"!=" -> '=/=';
		"&&" -> 'and';
		"||" -> 'or';
		"!"  -> 'not';
		_ ->    list_to_atom(OpChar)
	end.

-file("/usr/local/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/jaraki_lexer.erl", 318).
yystate() -> 120.

yystate(127, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(119, Ics, Line, Tlen+1, Action, Alen);
yystate(127, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,127};
yystate(126, [108|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 35, Tlen);
yystate(126, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(126, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,126};
yystate(125, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(125, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(125, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(125, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(125, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,125};
yystate(124, [124|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 36, Tlen);
yystate(124, [32|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 36, Tlen);
yystate(124, [9|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 36, Tlen);
yystate(124, [10|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line+1, Tlen+1, 36, Tlen);
yystate(124, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,124};
yystate(123, [101|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 35, Tlen);
yystate(123, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(123, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(123, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(123, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(123, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(123, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,123};
yystate(122, [98|Ics], Line, Tlen, _, _) ->
    yystate(126, Ics, Line, Tlen+1, 35, Tlen);
yystate(122, [97|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(122, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(122, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,122};
yystate(121, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(127, Ics, Line, Tlen+1, Action, Alen);
yystate(121, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,121};
yystate(120, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(112, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(117, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(106, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(108, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(124, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(124, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(124, Ics, Line+1, Tlen+1, Action, Alen);
yystate(120, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 82 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [C|Ics], Line, Tlen, Action, Alen) when C >= 84, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [C|Ics], Line, Tlen, Action, Alen) when C >= 106, C =< 108 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, [C|Ics], Line, Tlen, Action, Alen) when C >= 119, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(120, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,120};
yystate(119, [108|Ics], Line, Tlen, _, _) ->
    yystate(111, Ics, Line, Tlen+1, 15, Tlen);
yystate(119, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,119};
yystate(118, [101|Ics], Line, Tlen, _, _) ->
    yystate(110, Ics, Line, Tlen+1, 35, Tlen);
yystate(118, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(118, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,118};
yystate(117, [97|Ics], Line, Tlen, _, _) ->
    yystate(109, Ics, Line, Tlen+1, 35, Tlen);
yystate(117, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(117, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(117, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(117, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(117, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,117};
yystate(116, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(115, [103|Ics], Line, Tlen, _, _) ->
    yystate(123, Ics, Line, Tlen+1, 35, Tlen);
yystate(115, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(115, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,115};
yystate(114, [117|Ics], Line, Tlen, _, _) ->
    yystate(122, Ics, Line, Tlen+1, 35, Tlen);
yystate(114, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(114, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,114};
yystate(113, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(121, Ics, Line, Tlen+1, Action, Alen);
yystate(113, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,113};
yystate(112, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(111, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(111, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,111};
yystate(110, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 9, Tlen);
yystate(110, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,110};
yystate(109, [105|Ics], Line, Tlen, _, _) ->
    yystate(101, Ics, Line, Tlen+1, 35, Tlen);
yystate(109, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(109, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(109, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(109, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(109, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(109, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,109};
yystate(108, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(116, Ics, Line, Tlen+1, Action, Alen);
yystate(108, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,108};
yystate(107, [97|Ics], Line, Tlen, _, _) ->
    yystate(115, Ics, Line, Tlen+1, 35, Tlen);
yystate(107, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(107, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,107};
yystate(106, [111|Ics], Line, Tlen, _, _) ->
    yystate(114, Ics, Line, Tlen+1, 35, Tlen);
yystate(106, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(106, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,106};
yystate(105, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(113, Ics, Line, Tlen+1, Action, Alen);
yystate(105, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,105};
yystate(104, [124|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 36, Tlen);
yystate(104, [32|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 36, Tlen);
yystate(104, [9|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 36, Tlen);
yystate(104, [10|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line+1, Tlen+1, 36, Tlen);
yystate(104, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,104};
yystate(103, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(102, [108|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 35, Tlen);
yystate(102, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(102, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,102};
yystate(101, [110|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 35, Tlen);
yystate(101, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(101, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,101};
yystate(100, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(100, Ics, Line+1, Tlen+1, Action, Alen);
yystate(100, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(100, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,100};
yystate(99, [107|Ics], Line, Tlen, _, _) ->
    yystate(107, Ics, Line, Tlen+1, 35, Tlen);
yystate(99, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 106 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 108, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(99, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,99};
yystate(98, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 12, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 12, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 12, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 12, Tlen);
yystate(98, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,98};
yystate(97, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Tlen+1, Action, Alen);
yystate(97, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,97};
yystate(96, [124|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 36, Tlen);
yystate(96, [33|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 36, Tlen);
yystate(96, [32|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 36, Tlen);
yystate(96, [9|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 36, Tlen);
yystate(96, [10|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line+1, Tlen+1, 36, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,96};
yystate(95, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, [97|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 35, Tlen);
yystate(94, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(94, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,94};
yystate(93, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 6, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 6, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 6, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 6, Tlen);
yystate(93, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,93};
yystate(92, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line};
yystate(91, [99|Ics], Line, Tlen, _, _) ->
    yystate(99, Ics, Line, Tlen+1, 35, Tlen);
yystate(91, [97|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(91, [98|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(91, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(91, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,91};
yystate(90, [101|Ics], Line, Tlen, _, _) ->
    yystate(98, Ics, Line, Tlen+1, 35, Tlen);
yystate(90, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,90};
yystate(89, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 16, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 16, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 16, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 16, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,89};
yystate(88, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(87, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,87};
yystate(86, [115|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 35, Tlen);
yystate(86, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,86};
yystate(85, [110|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 35, Tlen);
yystate(85, [109|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 35, Tlen);
yystate(85, [102|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 35, Tlen);
yystate(85, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 108 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(85, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,85};
yystate(84, [92|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 37, Tlen);
yystate(84, [34|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 37, Tlen);
yystate(84, [10|Ics], Line, Tlen, _, _) ->
    yystate(100, Ics, Line+1, Tlen+1, 37, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(100, Ics, Line, Tlen+1, 37, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(100, Ics, Line, Tlen+1, 37, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(100, Ics, Line, Tlen+1, 37, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(100, Ics, Line, Tlen+1, 37, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line,84};
yystate(83, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 3, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 3, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 3, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 3, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,83};
yystate(82, [115|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 35, Tlen);
yystate(82, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,82};
yystate(81, [110|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 35, Tlen);
yystate(81, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,81};
yystate(80, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(79, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [115|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 35, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,78};
yystate(77, [116|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 35, Tlen);
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,77};
yystate(76, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(100, Ics, Line+1, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, [99|Ics], Line, Tlen, _, _) ->
    yystate(83, Ics, Line, Tlen+1, 35, Tlen);
yystate(75, [97|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(75, [98|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,75};
yystate(74, [108|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 35, Tlen);
yystate(74, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,74};
yystate(73, [108|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 15, Tlen);
yystate(73, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 15, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 15, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 15, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(40, Ics, Line, Tlen+1, 15, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 15, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,73};
yystate(72, [111|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 35, Tlen);
yystate(72, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,72};
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 11 ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,70};
yystate(69, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,69};
yystate(68, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(100, Ics, Line+1, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(68, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,68};
yystate(67, [105|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 35, Tlen);
yystate(67, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,67};
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 14, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 14, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 14, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 14, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,66};
yystate(65, [116|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,65};
yystate(64, [105|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 35, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,64};
yystate(63, [108|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 35, Tlen);
yystate(63, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,63};
yystate(62, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(61, [112|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 35, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,61};
yystate(60, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [61|Ics], Line, Tlen, _, _) ->
    yystate(116, Ics, Line, Tlen+1, 27, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,59};
yystate(58, [101|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 35, Tlen);
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,58};
yystate(57, [110|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 35, Tlen);
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,57};
yystate(56, [100|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 35, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,56};
yystate(55, [98|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 35, Tlen);
yystate(55, [97|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,55};
yystate(54, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(53, [111|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 35, Tlen);
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(51, [61|Ics], Line, Tlen, _, _) ->
    yystate(116, Ics, Line, Tlen+1, 31, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line,51};
yystate(50, [115|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,50};
yystate(49, [105|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,49};
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 5, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 5, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 5, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 5, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,48};
yystate(47, [117|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 35, Tlen);
yystate(47, [97|Ics], Line, Tlen, _, _) ->
    yystate(91, Ics, Line, Tlen+1, 35, Tlen);
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 116 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,47};
yystate(46, [122|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, [121|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 120 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,46};
yystate(45, [114|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 35, Tlen);
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(43, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(42, [108|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 35, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,42};
yystate(41, [114|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 35, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,41};
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,40};
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,39};
yystate(38, [115|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 35, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,38};
yystate(37, [116|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 35, Tlen);
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,37};
yystate(36, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(35, [46|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 33, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 33, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,35};
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 8, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,34};
yystate(33, [112|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 35, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,33};
yystate(32, [114|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 35, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,32};
yystate(31, [99|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, [97|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, [98|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,31};
yystate(30, [116|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 35, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,30};
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,29};
yystate(28, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line};
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [116|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 35, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,26};
yystate(25, [96|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(97, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(97, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(33, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(97, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(33, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(97, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(33, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(97, Ics, Line, Tlen+1, 35, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,25};
yystate(24, [117|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 35, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,24};
yystate(23, [105|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 35, Tlen);
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,23};
yystate(22, [101|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 35, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,22};
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 10, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 10, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 10, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 10, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,21};
yystate(20, [43|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 28, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,20};
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(19, Ics, Line, Tlen+1, 34, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,19};
yystate(18, [97|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 35, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,18};
yystate(17, [116|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 35, Tlen);
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,17};
yystate(16, [101|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 35, Tlen);
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,16};
yystate(15, [116|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 35, Tlen);
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,15};
yystate(14, [109|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 35, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,14};
yystate(13, [111|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, [109|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, [110|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, [108|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, [97|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 107 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(11, [42|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 24, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,11};
yystate(10, [111|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 35, Tlen);
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,10};
yystate(9, [117|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 35, Tlen);
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,9};
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 13, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 13, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 13, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 13, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,8};
yystate(7, [97|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 35, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,7};
yystate(6, [96|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(95, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(95, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(1, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(95, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(1, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(95, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(1, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(95, Ics, Line, Tlen+1, 35, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,6};
yystate(5, [114|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 35, Tlen);
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,5};
yystate(4, [45|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 28, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,4};
yystate(3, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 11, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 11, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 11, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 11, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,2};
yystate(1, [111|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 35, Tlen);
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,1};
yystate(0, [116|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 35, Tlen);
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(40, Ics, Line, Tlen+1, 35, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(29, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(33, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars, TokenLine);
yyaction(34, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_34(TokenChars, TokenLine);
yyaction(35, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars, TokenLine);
yyaction(36, _, _, _) ->
    yyaction_36();
yyaction(37, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_37(TokenChars, TokenLen, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("src/jaraki_lexer.xrl", 60).
yyaction_0(TokenChars, TokenLine) ->
     { token, { package, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_1/2}).
-file("src/jaraki_lexer.xrl", 61).
yyaction_1(TokenChars, TokenLine) ->
     { token, { import, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_2/2}).
-file("src/jaraki_lexer.xrl", 62).
yyaction_2(TokenChars, TokenLine) ->
     { token, { class, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_3/2}).
-file("src/jaraki_lexer.xrl", 63).
yyaction_3(TokenChars, TokenLine) ->
     { token, { public, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_4/2}).
-file("src/jaraki_lexer.xrl", 64).
yyaction_4(TokenChars, TokenLine) ->
     { token, { static, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_5/2}).
-file("src/jaraki_lexer.xrl", 65).
yyaction_5(TokenChars, TokenLine) ->
     { token, { void, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_6/2}).
-file("src/jaraki_lexer.xrl", 66).
yyaction_6(TokenChars, TokenLine) ->
     { token, { main, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_7/2}).
-file("src/jaraki_lexer.xrl", 67).
yyaction_7(TokenChars, TokenLine) ->
     { token, { int_t, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_8/2}).
-file("src/jaraki_lexer.xrl", 68).
yyaction_8(TokenChars, TokenLine) ->
     { token, { float_t, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_9/2}).
-file("src/jaraki_lexer.xrl", 69).
yyaction_9(TokenChars, TokenLine) ->
     { token, { double_t, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_10/2}).
-file("src/jaraki_lexer.xrl", 70).
yyaction_10(TokenChars, TokenLine) ->
     { token, { 'if', TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_11/2}).
-file("src/jaraki_lexer.xrl", 71).
yyaction_11(TokenChars, TokenLine) ->
     { token, { for, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_12/2}).
-file("src/jaraki_lexer.xrl", 72).
yyaction_12(TokenChars, TokenLine) ->
     { token, { else, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_13/2}).
-file("src/jaraki_lexer.xrl", 73).
yyaction_13(TokenChars, TokenLine) ->
     { token, { true, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_14/2}).
-file("src/jaraki_lexer.xrl", 74).
yyaction_14(TokenChars, TokenLine) ->
     { token, { false, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_15/2}).
-file("src/jaraki_lexer.xrl", 75).
yyaction_15(TokenChars, TokenLine) ->
     { token, { print, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_16/2}).
-file("src/jaraki_lexer.xrl", 76).
yyaction_16(TokenChars, TokenLine) ->
     { token, { println, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_17/2}).
-file("src/jaraki_lexer.xrl", 79).
yyaction_17(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_18/2}).
-file("src/jaraki_lexer.xrl", 80).
yyaction_18(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_19/2}).
-file("src/jaraki_lexer.xrl", 81).
yyaction_19(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_20/2}).
-file("src/jaraki_lexer.xrl", 82).
yyaction_20(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_21/2}).
-file("src/jaraki_lexer.xrl", 83).
yyaction_21(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_22/2}).
-file("src/jaraki_lexer.xrl", 84).
yyaction_22(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_23/2}).
-file("src/jaraki_lexer.xrl", 85).
yyaction_23(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_24/2}).
-file("src/jaraki_lexer.xrl", 86).
yyaction_24(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_25/2}).
-file("src/jaraki_lexer.xrl", 87).
yyaction_25(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_26/2}).
-file("src/jaraki_lexer.xrl", 88).
yyaction_26(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_27/2}).
-file("src/jaraki_lexer.xrl", 89).
yyaction_27(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_28/2}).
-file("src/jaraki_lexer.xrl", 90).
yyaction_28(TokenChars, TokenLine) ->
     { token, { add_op, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_29/2}).
-file("src/jaraki_lexer.xrl", 91).
yyaction_29(TokenChars, TokenLine) ->
     { token, { mult_op, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_30/2}).
-file("src/jaraki_lexer.xrl", 92).
yyaction_30(TokenChars, TokenLine) ->
     { token, { inc_op, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_31/2}).
-file("src/jaraki_lexer.xrl", 93).
yyaction_31(TokenChars, TokenLine) ->
     { token, { comp_op, TokenLine, op (TokenChars) } } .

-compile({inline,yyaction_32/2}).
-file("src/jaraki_lexer.xrl", 94).
yyaction_32(TokenChars, TokenLine) ->
     { token, { bool_op, TokenLine, op (TokenChars) } } .

-compile({inline,yyaction_33/2}).
-file("src/jaraki_lexer.xrl", 98).
yyaction_33(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_34/2}).
-file("src/jaraki_lexer.xrl", 99).
yyaction_34(TokenChars, TokenLine) ->
     { token, { float, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_35/2}).
-file("src/jaraki_lexer.xrl", 101).
yyaction_35(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_36/0}).
-file("src/jaraki_lexer.xrl", 102).
yyaction_36() ->
     skip_token .

-compile({inline,yyaction_37/3}).
-file("src/jaraki_lexer.xrl", 103).
yyaction_37(TokenChars, TokenLen, TokenLine) ->
     build_text (text, TokenChars, TokenLine, TokenLen) .

-file("/usr/local/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 282).
