-module(listarprimos).

-compile(export_all).

-import(loop, [for/3, while/2]).

main(Var_args1) ->
    st:new(),
    begin Var_a1 = 2, st:insert({"a", Var_a1}) end,
    begin Var_i1 = 0, st:insert({"i", Var_i1}) end,
    begin Var_n1 = 10, st:insert({"n", Var_n1}) end,
    io:format("Primos~n"),
    begin
      while(fun () -> st:get("i") < st:get("n") end,
	    fun () ->
		    Var_nota34 = st:get("nota3"),
		    Var_a2 = st:get("a"),
		    Var_t2 = st:get("t"),
		    Var_b4 = st:get("b"),
		    Var_args2 = st:get("args"),
		    Var_mediaFinal4 = st:get("mediaFinal"),
		    Var_nota24 = st:get("nota2"),
		    Var_denominador5 = st:get("denominador"),
		    Var_numerador5 = st:get("numerador"),
		    Var_a3 = st:get("a"),
		    Var_a2 = st:get("a"),
		    Var_a2 = st:get("a"),
		    Var_b2 = st:get("b"),
		    Var_c4 = st:get("c"),
		    Var_Args2 = st:get("Args"),
		    Var_nota14 = st:get("nota1"),
		    Var_media4 = st:get("media"),
		    Var_x2 = st:get("x"),
		    Var_s5 = st:get("s"),
		    Var_i2 = st:get("i"),
		    Var_n2 = st:get("n"),
		    Var_temp2 = st:get("temp"),
		    st:insert({"nota3", Var_nota34}),
		    st:insert({"a", Var_a1}),
		    st:insert({"t", Var_t2}),
		    st:insert({"b", Var_b3}),
		    st:insert({"args", Var_args2}),
		    st:insert({"mediaFinal", Var_mediaFinal4}),
		    st:insert({"nota2", Var_nota24}),
		    st:insert({"denominador", Var_denominador5}),
		    st:insert({"numerador", Var_numerador5}),
		    st:insert({"a", Var_a2}),
		    st:insert({"a", Var_a1}),
		    st:insert({"a", Var_a2}),
		    st:insert({"b", Var_b4}),
		    st:insert({"c", Var_c4}),
		    st:insert({"temp", Var_temp2}),
		    st:insert({"Args", Var_Args2}),
		    st:insert({"nota1", Var_nota14}),
		    st:insert({"media", Var_media4}),
		    st:insert({"x", Var_x2}),
		    st:insert({"s", Var_s5}),
		    st:insert({"i", Var_i2}),
		    st:insert({"n", Var_n2}),
		    st:insert({"temp", Var_temp1}),
		    case ehprimo(Var_a2) == 0 of
		      true ->
			  io:format("Eh primo: "),
			  io:format("~p~n", [Var_a2]),
			  begin
			    Var_i3 = Var_i2 + 1, st:insert({"i", Var_i3})
			  end;
		      false -> no_operation
		    end,
		    begin Var_a3 = Var_a2 + 1, st:insert({"a", Var_a3}) end
	    end),
      Var_nota35 = st:get("nota3"),
      Var_a2 = st:get("a"),
      Var_t3 = st:get("t"),
      Var_b4 = st:get("b"),
      Var_args3 = st:get("args"),
      Var_mediaFinal5 = st:get("mediaFinal"),
      Var_nota25 = st:get("nota2"),
      Var_denominador6 = st:get("denominador"),
      Var_numerador6 = st:get("numerador"),
      Var_a3 = st:get("a"),
      Var_a2 = st:get("a"),
      Var_a4 = st:get("a"),
      Var_b5 = st:get("b"),
      Var_c5 = st:get("c"),
      Var_temp3 = st:get("temp"),
      Var_Args3 = st:get("Args"),
      Var_nota15 = st:get("nota1"),
      Var_media5 = st:get("media"),
      Var_x3 = st:get("x"),
      Var_s6 = st:get("s"),
      Var_i4 = st:get("i"),
      Var_n3 = st:get("n"),
      Var_temp2 = st:get("temp")
    end.

ehprimo(Var_m1) ->
    begin
      Var_primo1 = 0, st:insert({"primo", Var_primo1})
    end,
    begin
      st:insert({"j", 2}),
      for(fun () -> st:get("j") =< st:get("m") - 1 end,
	  fun () -> st:insert({"j", st:get("j") + 1}) end,
	  fun () ->
		  Var_nota36 = st:get("nota3"),
		  Var_a2 = st:get("a"),
		  Var_t4 = st:get("t"),
		  Var_b4 = st:get("b"),
		  Var_mediaFinal6 = st:get("mediaFinal"),
		  Var_args4 = st:get("args"),
		  Var_nota26 = st:get("nota2"),
		  Var_denominador7 = st:get("denominador"),
		  Var_numerador7 = st:get("numerador"),
		  Var_j2 = st:get("j"),
		  Var_a3 = st:get("a"),
		  Var_a2 = st:get("a"),
		  Var_a3 = st:get("a"),
		  Var_b5 = st:get("b"),
		  Var_c6 = st:get("c"),
		  Var_primo2 = st:get("primo"),
		  Var_temp4 = st:get("temp"),
		  Var_Args4 = st:get("Args"),
		  Var_nota16 = st:get("nota1"),
		  Var_media6 = st:get("media"),
		  Var_x4 = st:get("x"),
		  Var_s7 = st:get("s"),
		  Var_i5 = st:get("i"),
		  Var_m2 = st:get("m"),
		  Var_n4 = st:get("n"),
		  Var_temp2 = st:get("temp"),
		  case Var_m2 rem Var_j2 == 0 of
		    true ->
			begin
			  Var_primo3 = Var_primo2 + 1,
			  st:insert({"primo", Var_primo3})
			end;
		    false -> no_operation
		  end,
		  st:insert({"s", Var_s7}),
		  st:insert({"b", Var_b3}),
		  st:insert({"args", Var_args3}),
		  st:insert({"mediaFinal", Var_mediaFinal5}),
		  st:insert({"denominador", Var_denominador6}),
		  st:insert({"a", Var_a2}),
		  st:insert({"j", Var_j2}),
		  st:insert({"x", Var_x4}),
		  st:insert({"media", Var_media6}),
		  st:insert({"a", Var_a2}),
		  st:insert({"Args", Var_Args3}),
		  st:insert({"args", Var_args4}),
		  st:insert({"x", Var_x3}),
		  st:insert({"s", Var_s6}),
		  st:insert({"i", Var_i4}),
		  st:insert({"b", Var_b4}),
		  st:insert({"i", Var_i5}),
		  st:insert({"m", Var_m2}),
		  st:insert({"n", Var_n3}),
		  st:insert({"temp", Var_temp1}),
		  st:insert({"c", Var_c6}),
		  st:insert({"t", Var_t4}),
		  st:insert({"nota1", Var_nota16}),
		  st:insert({"mediaFinal", Var_mediaFinal6}),
		  st:insert({"a", Var_a1}),
		  st:insert({"a", Var_a2}),
		  st:insert({"temp", Var_temp4}),
		  st:insert({"numerador", Var_numerador7}),
		  st:insert({"n", Var_n4}),
		  st:insert({"denominador", Var_denominador7}),
		  st:insert({"b", Var_b4}),
		  st:insert({"c", Var_c5}),
		  st:insert({"primo", Var_primo3}),
		  st:insert({"temp", Var_temp3}),
		  st:insert({"nota1", Var_nota15}),
		  st:insert({"media", Var_media5}),
		  st:insert({"Args", Var_Args4}),
		  st:insert({"nota3", Var_nota36}),
		  st:insert({"a", Var_a1}),
		  st:insert({"nota3", Var_nota35}),
		  st:insert({"nota2", Var_nota26}),
		  st:insert({"t", Var_t3}),
		  st:insert({"nota2", Var_nota25}),
		  st:insert({"numerador", Var_numerador6})
	  end),
      st:delete("j"),
      Var_s8 = st:get("s"),
      Var_b4 = st:get("b"),
      Var_args4 = st:get("args"),
      Var_mediaFinal6 = st:get("mediaFinal"),
      Var_denominador7 = st:get("denominador"),
      Var_a3 = st:get("a"),
      Var_x5 = st:get("x"),
      Var_media7 = st:get("media"),
      Var_a3 = st:get("a"),
      Var_Args4 = st:get("Args"),
      Var_args5 = st:get("args"),
      Var_x4 = st:get("x"),
      Var_s7 = st:get("s"),
      Var_i5 = st:get("i"),
      Var_b5 = st:get("b"),
      Var_i6 = st:get("i"),
      Var_m3 = st:get("m"),
      Var_n4 = st:get("n"),
      Var_temp2 = st:get("temp"),
      Var_c7 = st:get("c"),
      Var_t5 = st:get("t"),
      Var_nota17 = st:get("nota1"),
      Var_mediaFinal7 = st:get("mediaFinal"),
      Var_a2 = st:get("a"),
      Var_a3 = st:get("a"),
      Var_temp5 = st:get("temp"),
      Var_numerador8 = st:get("numerador"),
      Var_n5 = st:get("n"),
      Var_denominador8 = st:get("denominador"),
      Var_b5 = st:get("b"),
      Var_c6 = st:get("c"),
      Var_primo4 = st:get("primo"),
      Var_temp4 = st:get("temp"),
      Var_nota16 = st:get("nota1"),
      Var_media6 = st:get("media"),
      Var_Args5 = st:get("Args"),
      Var_nota37 = st:get("nota3"),
      Var_a2 = st:get("a"),
      Var_nota36 = st:get("nota3"),
      Var_nota27 = st:get("nota2"),
      Var_t4 = st:get("t"),
      Var_nota26 = st:get("nota2"),
      Var_numerador7 = st:get("numerador")
    end,
    st:get("primo").

